/*
#define TRIGGER_PIN_SHIFT 9
#define ECHO_PIN_SHIFT 10
#define TRIGGER_PIN_PITCH 11
#define ECHO_PIN_PITCH 12
#define MAX_DISTANCE 60
#define VOLUME_PIN A0
#define OCTAVE_PIN A1
#define TREMOLO_PIN A2
#define SHIFT_PIN A3
#define WAVE_PIN 9
*/
